# Usa una imagen base de Ubuntu
FROM ubuntu:latest

# Actualiza el sistema e instala Apache, ModSecurity, mod_evasive y herramientas necesarias
RUN apt update && apt upgrade -y && \
    apt install -y apache2 libapache2-mod-security2 libapache2-mod-evasive git curl

# Habilita los módulos necesarios para Apache
RUN a2enmod headers ssl security2 evasive

# Verifica si los módulos están habilitados correctamente
RUN apache2ctl -M | grep evasive
RUN apache2ctl -M | grep security2

# Elimina cualquier archivo existente en /etc/modsecurity/crs y luego clona el repositorio de reglas OWASP CRS
RUN rm -rf /etc/modsecurity/crs && \
    git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /etc/modsecurity/crs

# Mueve el archivo crs-setup.conf.example a su ubicación correcta
RUN mv /etc/modsecurity/crs/crs-setup.conf.example /etc/modsecurity/crs/crs-setup.conf

# Mueve las reglas a su ubicación correcta
RUN mv /etc/modsecurity/crs/rules /etc/modsecurity/rules

# Copia el archivo de configuración recomendado de ModSecurity
RUN cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf

# Configura ModSecurity para activar las reglas de OWASP
RUN sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf

# Copia los archivos de configuración para Apache
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./mod_evasive.conf /etc/apache2/conf-available/mod_evasive.conf

# Habilita la configuración de mod_evasive
RUN a2enconf mod_evasive

# Habilita el sitio por defecto
RUN a2ensite 000-default.conf

# Expone los puertos 80 (HTTP) y 443 (HTTPS)
EXPOSE 80 443

# Comando para mantener Apache en primer plano
CMD ["apachectl", "-D", "FOREGROUND"]
